basic:
    name: 'Leslie Little III'
    breakpoints:
        - 640
        - 1024
        - 1200
    pages:
        - 'https://www.gerhold.org/quaerat-eos-nemo-aut-laborum-voluptatem-ea-similique'
        - 'https://www.emard.biz/placeat-itaque-quos-dolorem-aut-est-ut-illo'
    monitoring:
        days: {  }
        type: ''
advanced:
    mask: ''
    remove: ''
    isolate: ''
    delay: 15
    scroll: true
    headers:
        - { header: '', value: '' }
    cookies: ''
    custom_js: ''
    custom_css: ''
    mock_content: ''
    performance:
        workers_production: 30
        workers_nonproduction: 10
        workers_production_delay: 0
        workers_nonproduction_delay: 0
    stabilize: true
